name: smart_ix
description: RiverPod Example project

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.5
  firebase_core: ^1.22.0
  firebase_auth: ^3.8.0
  json_annotation:
  logger: ^1.1.0
  provider: ^6.0.3
  hive_flutter: ^1.1.0
  cloud_firestore: ^3.4.7
  weather: ^2.0.1
  geolocator: ^9.0.1
  url_launcher: ^6.1.5
  qr_code_scanner: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  hive_generator: ^1.1.3
  json_serializable: ^6.3.2
  build_runner: ^2.2.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/weather/