// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOsr0b3zZswzAtEHsWZPBqMkV2P7F4QP0',
    appId: '1:188895466760:web:d0e4c34ca04ec4e081c8bd',
    messagingSenderId: '188895466760',
    projectId: 'smart-ix',
    authDomain: 'smart-ix.firebaseapp.com',
    databaseURL: 'https://smart-ix-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smart-ix.appspot.com',
    measurementId: 'G-ERKJJ48JDY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoz_O8ILAMeHS6rjRSvWiZG90vm-NHCMc',
    appId: '1:188895466760:android:ebf6767005f104ad81c8bd',
    messagingSenderId: '188895466760',
    projectId: 'smart-ix',
    databaseURL: 'https://smart-ix-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smart-ix.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqO7jR_C4gxcVzuauqnwqzIfTcmOMWjK0',
    appId: '1:188895466760:ios:c5255fda661e79b881c8bd',
    messagingSenderId: '188895466760',
    projectId: 'smart-ix',
    databaseURL: 'https://smart-ix-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smart-ix.appspot.com',
    androidClientId: '188895466760-1l510646g7ldmlmhn8e0hbd86k6uv6qs.apps.googleusercontent.com',
    iosClientId: '188895466760-qtb1inklk4mcb5gtckcvnme6d2qaikkj.apps.googleusercontent.com',
    iosBundleId: 'com.smartix.smartIx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqO7jR_C4gxcVzuauqnwqzIfTcmOMWjK0',
    appId: '1:188895466760:ios:c5255fda661e79b881c8bd',
    messagingSenderId: '188895466760',
    projectId: 'smart-ix',
    databaseURL: 'https://smart-ix-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smart-ix.appspot.com',
    androidClientId: '188895466760-1l510646g7ldmlmhn8e0hbd86k6uv6qs.apps.googleusercontent.com',
    iosClientId: '188895466760-qtb1inklk4mcb5gtckcvnme6d2qaikkj.apps.googleusercontent.com',
    iosBundleId: 'com.smartix.smartIx',
  );
}
